---
updates:
  - commit-message:
      include: scope
      prefix: docker
    directory: /
    package-ecosystem: docker
    schedule: &interval
      interval: daily
  - commit-message:
      include: scope
      prefix: github-actions
    directory: /
    package-ecosystem: github-actions
    schedule: *interval
  - commit-message:
      include: scope
      prefix: gitsubmodule
    directory: /
    package-ecosystem: gitsubmodule
    schedule: *interval
  - commit-message:
      include: scope
      prefix: pip
    directory: /
    package-ecosystem: pip
    schedule: *interval
version: 2
