---
updates:
  - directory: /
    package-ecosystem: docker
    schedule:
      interval: daily
  - directory: /
    package-ecosystem: github-actions
    schedule:
      interval: daily
  - directory: /
    package-ecosystem: gitsubmodule
    schedule:
      interval: daily
  - directory: /
    package-ecosystem: pip
    schedule:
      interval: daily
version: 2
