gitConfig:
  push.autoSetupRemote: "true"
github:
  prebuilds:
    addBadge: true
    addCheck: true
    addComment: true
    branches: true
    master: true
    pullRequests: true
    pullRequestsFromForks: true
tasks:
  - env:
      CC: ccache clang
      CXX: ccache clang++
      CXXFLAGS: -std=c++2b
    init: tools/boot.sh
