---
gitConfig:
  advice.detachedHead: "true"
  advice.ignoredHook: "false"
  advice.skippedCherryPicks: "false"
  checkout.defaultRemote: origin
  core.ignorecase: "true"
  # diff "hex".binary: "true"
  # diff "hex".cachetextconv: "true"
  # diff "hex".textconv: hexdump
  # diff "json".textconv: jq --sort-keys '.'
  diff.renameLimit: "1522"
  diff.submodule: diff
  fetch.recurseSubmodules: "false"
  init.defaultBranch: stable
  pull.rebase: "true"
  push.autoSetupRemote: "true"
  push.default: simple
  push.recurseSubmodules: "false"
  rebase.autoSquash: "true"
  rebase.autoStash: "true"
  rebase.backend: apply
  rebase.missingCommitsCheck: error
  rebase.updateRefs: "true"
  status.submoduleSummary: "true"
  submodule.recurse: "true"
github:
  prebuilds:
    addBadge: true
    addCheck: prevent-merge-on-error
    addComment: true
    branches: true
    master: true
    pullRequests: true
    pullRequestsFromForks: true
image: asakatida/chimera:latest
tasks:
  - env:
      CC: clang
      CMAKE_BUILD_TYPE: Debug
      CXX: clang++
      CXXFLAGS: >
        -std=c++20
        -fsanitize-coverage=no-prune
        -fsanitize-coverage=trace-cmp
        -fsanitize-coverage=trace-div
        -fsanitize-coverage=trace-gep
        -fsanitize-coverage=trace-loads
        -fsanitize-coverage=trace-stores
    init: tools/boot.sh
vscode:
  extensions:
    - cschlosser.doxdocgen
    - DavidAnson.vscode-markdownlint
    - GitHub.copilot
    - jeff-hykin.better-cpp-syntax
    - ms-azuretools.vscode-docker
    - ms-python.python
    - ms-python.vscode-pylance
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
    - ms-vscode.cmake-tools
    - ms-vscode.cpptools
    - ms-vscode.cpptools-extension-pack
    - ms-vscode.cpptools-themes
    - twxs.cmake
