---
github:
  prebuilds:
    addBadge: true
    addCheck: prevent-merge-on-error
    addComment: true
    branches: true
    master: true
    pullRequests: true
    pullRequestsFromForks: true
image: asakatida/chimera:latest
tasks:
  - before: >
      /opt/virtualenv/bin/python tools/before.py &&
      export PATH="/opt/virtualenv/bin:${PATH}"
    init: /opt/virtualenv/bin/python tools/boot.py
vscode:
  extensions:
    - cschlosser.doxdocgen
    - DavidAnson.vscode-markdownlint
    - GitHub.copilot
    - jeff-hykin.better-cpp-syntax
    - ms-azuretools.vscode-docker
    - ms-python.python
    - ms-python.vscode-pylance
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
    - ms-vscode.cmake-tools
    - ms-vscode.cpptools
    - ms-vscode.cpptools-extension-pack
    - ms-vscode.cpptools-themes
    - twxs.cmake
