language: cpp
sudo: false

compiler: clang

matrix:
  include:
    - addons:
        apt:
          sources:
            - llvm-toolchain-trusty-6.0
            - ubuntu-toolchain-r-test
          packages:
            - clang-6.0
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - cmake .
  - make -j3
  - make check
