language: cpp
sudo: false

compiler: clang

env:
  - CPPFLAGS="-std=c++17"
  - CXXFLAGS="-Wall -Wextra"

matrix:
  include:
    - addons:
        apt:
          sources:
            - llvm-toolchain-trusty-6.0
            - ubuntu-toolchain-r-test
          packages:
            - clang-6.0
      env:
        - CC=clang-6.0
        - CXX=clang++-6.0
    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - CC=gcc-8
        - CXX=g++-8

script:
  - cmake .
  - make -j3
  - make check
