language: cpp

compiler: clang

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

before_install:
  - eval "${MATRIX_EVAL}"
  - wget https://cmake.org/files/v3.10/cmake-3.10.0.tar.gz
  - tar -xzf cmake-3.10.0.tar.gz
  - pushd cmake-3.10.0 && cmake . && make && sudo make install && popd

script:
  - cmake .
  - make
  - make check
