language: cpp
sudo: false

matrix:
  include:
    - addons:
        apt:
          sources:
            - llvm-toolchain-trusty-6.0
            - ubuntu-toolchain-r-test
          packages:
            - clang-6.0
      compiler: clang
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"
    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      compiler: gcc
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="-std=c++17 -Wall -Wextra"
  - make -j3
  - make check
