---
extends: default

rules:
  braces:
    forbid: non-empty
    max-spaces-inside-empty: 0
    min-spaces-inside-empty: 0
  brackets:
    forbid: non-empty
    max-spaces-inside-empty: 0
    min-spaces-inside-empty: 0
  comments:
    level: error
  comments-indentation:
    level: error
  document-start: disable
  empty-values: enable
  float-values: enable
  key-ordering: enable
  line-length:
    level: warning
    max: 120
  octal-values: enable
  quoted-strings:
    quote-type: double
    required: only-when-needed
  truthy:
    check-keys: false
    level: error
