---
extends: default

rules:
  braces:
    forbid: non-empty
    max-spaces-inside-empty: 0
    min-spaces-inside-empty: 0
  brackets:
    forbid: non-empty
    max-spaces-inside-empty: 0
    min-spaces-inside-empty: 0
  comments:
    level: error
  comments-indentation:
    level: error
  empty-values: enable
  float-values: enable
  key-ordering: enable
  line-length:
    ignore: |
      .github/workflows/*
    level: error
    max: 90
  octal-values: enable
  quoted-strings:
    quote-type: double
    required: only-when-needed
  truthy:
    level: error
