---
- hosts: localhost
  tasks:
    - set_fact:
        py_version: 3.12
    - become: true
      block:
        - apt_repository:
            repo: ppa:deadsnakes/nightly
        - package:
            name:
              - python{{ py_version }}-dev
              - python{{ py_version }}-venv
      when: ansible_facts.os_family == 'Debian'
    - block:
        - args:
            creates: /opt/homebrew/Cellar/pyenv
          command: brew install pyenv
        - args:
            creates: "{{ lookup('env', 'HOME') }}/.pyenv/versions/{{ py_version }}-dev"
          command: pyenv install {{ py_version }}-dev
      when: ansible_facts.os_family == 'Darwin'
