---
# yamllint disable rule:key-ordering
- hosts: localhost
  name: Boot localhost for building
  tasks:
    - name: Install core packages
      ansible.builtin.pip:
        requirements: "{{ playbook_dir }}/../requirements.core.txt"
        state: present
    - name: Install packages
      ansible.builtin.pip:
        requirements: "{{ playbook_dir }}/../requirements.txt"
        state: present
    - name: Update submodules  # noqa: command-instead-of-module
      ansible.builtin.command: git submodule update --init
    - name: Gather chimera path
      ansible.builtin.command: python3 {{ playbook_dir }}/chimera_path.py
      register: chimera_path
    - name: Set CC, CXX, and CXXFLAGS
      ansible.builtin.set_fact:
        cxxflags: >
          {{ lookup('env', 'CXXFLAGS') | default('') }}
          -DCHIMERA_PATH={{ playbook_dir }}/../stdlib:{{ chimera_path.stdout }}
    - name: Create debug build directory
      ansible.builtin.command: >
        {{ playbook_dir }}/cmake.sh {{ playbook_dir }}/../build/debug -Wdev -Werror=dev
      args:
        creates: "{{ playbook_dir }}/../build/debug"
      environment:
        CXXFLAGS: "{{ cxxflags }}"
    - name: Create release build directory
      ansible.builtin.command: >
        {{ playbook_dir }}/cmake.sh {{ playbook_dir }}/../build/release
      args:
        creates: "{{ playbook_dir }}/../build/release"
      environment:
        CMAKE_BUILD_TYPE: MinSizeRel
        CXXFLAGS: "{{ cxxflags }} -DNDEBUG"
    - name: Build project
      ansible.builtin.command: ninja -C {{ playbook_dir }}/../{{ item }} -j1 -k0
      failed_when: false
      loop:
        - build/debug
        - build/release
# yamllint enable rule:key-ordering
