FROM {% if item.requires %}chimera/{{ item.requires }}-{% endif %}{{ item.distro }}:{{ item.tag }}

{% if item.distro != 'alpine' %}
RUN apt-get update
{% endif %}
RUN {{ item.package_command }} {{ item.dependencies }}

{% for environ, value in item.environment.items() %}
ENV {{ environ }} "{{ value }}"
{% endfor %}
