---
jobs:
  cleanup-actions:
    permissions:
      actions: write
    runs-on: ubuntu-22.04
    steps:
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        name: Cleanup
        run: >
          set -o pipefail;
          gh api "repos/${REPO}/actions/runs" --paginate -q '
            .workflow_runs |
            map(
              select(
                .conclusion != null and
                .head_branch != null and
                .status != "in_progress"
              ) |
              select(
                (.run_started_at | fromdate) < (now - 60 * 60 * 24 * 60) or
                (.head_branch != "stable" and .conclusion == "cancelled") or
                (
                  (.run_started_at | fromdate) < (now - 60 * 60 * 24 * 7) and
                  .head_branch != "stable"
                ) or (
                  (.path | startswith(".github/workflows/actions")) and
                  (.run_started_at | fromdate) < (now - 60 * 60 * 24 * 2)
                ) or (
                  (.run_started_at | fromdate) < (now - 60 * 60 * 24 * 3) and
                  (
                    (.head_branch == "requirements-txt") or
                    (.head_branch == "utf8-generate-grammar") or
                    (.head_branch | startswith("corpus-")) or
                    (.head_branch | startswith("dependabot/")) or
                    (.head_branch | startswith("pin-0."))
                  )
                )
              )
            )[]
          ' |
          jq --join-output --slurp 'map(.url) | join("\u0000")' |
          xargs --max-args=1 --max-procs=2 --no-run-if-empty --null --verbose --
          gh api -X DELETE
  cleanup-packages:
    permissions:
      packages: write
    runs-on: ubuntu-22.04
    steps:
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
        name: Cleanup
        run: >
          set -o pipefail;
          gh api "users/${OWNER}/packages/container/chimera/versions" --paginate -q '
            map(
              select(
                (.metadata.container.tags | map(test("^[A-Za-z0-9]+$")) | all) and
                (.metadata.container.tags | length > 0) and
                (.updated_at | fromdate) < (now - 60 * 60 * 24 * 5)
              )
            )[]
          ' |
          jq --join-output --slurp 'map(.url) | join("\u0000")' |
          xargs --max-args=1 --max-procs=2 --no-run-if-empty --null --verbose --
          gh api -X DELETE
  rerun-actions:
    permissions:
      actions: write
    runs-on: ubuntu-22.04
    steps:
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        name: Rerun
        run: >
          set -o pipefail;
          gh api "repos/${REPO}/actions/runs" --paginate -q '
            .workflow_runs[] |
            select(
              (.run_started_at | fromdate) > (now - 60 * 60 * 24 * 14) and
              .head_branch == "stable" and
              .conclusion == "cancelled"
            )
          ' |
          jq --join-output --slurp '
            group_by(.path) |
            map(sort_by(.rerun_url) | first) |
            map(.rerun_url) | join("\u0000")
          ' |
          xargs --max-args=1 --max-procs=2 --no-run-if-empty --null --verbose --
          gh api -X POST

name: Meta Actions

# yamllint disable-line rule:truthy
on:
  push:
    paths:
      - .github/workflows/actions.yml
  schedule:
    - cron: 20 2,8,14,20 * * *
  workflow_dispatch: ~
