---
jobs:
  cleanup-actions:
    concurrency:
      cancel-in-progress: ${{ github.ref != 'refs/heads/stable' }}
      group: ${{ github.workflow }}-actions-${{ github.ref }}
    permissions:
      actions: write
    runs-on: ubuntu-22.04
    steps:
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
        name: Cleanup
        run: >
          gh api "repos/$OWNER/$REPO/actions/runs" --paginate -q '
            .workflow_runs |
            map(
              select(
                .conclusion != null and
                .status != "in_progress"
              ) |
              select(
                (.run_started_at | fromdate) < (now - 60 * 60 * 24 * 60) or
                (
                  (.run_started_at | fromdate) < (now - 60 * 60 * 24 * 7) and
                  .head_branch != "stable"
                ) or (
                  (.run_started_at | fromdate) < (now - 60 * 60 * 24 * 3) and
                  (
                    (.head_branch == "requirements-txt") or
                    (.head_branch == "utf8-generate-grammar") or
                    (.head_branch | startswith("corpus-new-")) or
                    (.head_branch | startswith("corpus-retest-")) or
                    (.head_branch | startswith("dependabot/")) or
                    (.head_branch | startswith("gather-")) or
                    (.head_branch | startswith("pin-0."))
                  )
                )
              ) |
              .url
            )[]
          ' |
          xargs --max-lines=1 --max-procs=2 --no-run-if-empty --verbose --
          gh api -X DELETE
  cleanup-packages:
    concurrency:
      cancel-in-progress: ${{ github.ref != 'refs/heads/stable' }}
      group: ${{ github.workflow }}-packages-${{ github.ref }}
    permissions:
      packages: write
    runs-on: ubuntu-22.04
    steps:
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        name: Cleanup
        run: >
          gh api /user/packages/container/chimera-testing/versions --paginate -q '
            map(
              select(
                .metadata.container.tags == [] or
                (.updated_at | fromdate) < (now - 60 * 60 * 24 * 7)
              ) |
              .url
            )[]
          ' |
          xargs --max-lines=1 --max-procs=2 --no-run-if-empty --verbose --
          gh api -X DELETE
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        name: Cleanup
        run: >
          gh api /user/packages/container/chimera/versions --paginate -q '
            map(
              select(
                .metadata.container.tags == [] and
                (.updated_at | fromdate) < (now - 60 * 60 * 24 * 30)
              ) |
              .url
            )[]
          ' |
          xargs --max-lines=1 --max-procs=2 --no-run-if-empty --verbose --
          gh api -X DELETE

name: Meta Actions

# yamllint disable-line rule:truthy
on:
  push:
    paths:
      - .github/workflows/actions.yml
  schedule:
    - cron: 20 14 * * *
  workflow_dispatch: ~
