---
jobs:
  cleanup-actions:
    permissions:
      actions: write
    runs-on: ubuntu-22.04
    steps:
      - env:
          BRANCH: ${{ github.event.ref }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        name: Cleanup
        run: >
          set -o pipefail;
          gh api "repos/${REPO}/actions/runs" --paginate -q '
            .workflow_runs[] |
            select(
              .conclusion == null and
              .path != ".github/workflows/actions-pr-close.yml" and
              .path != ".github/workflows/actions-branch-delete.yml" and
              .head_branch != "stable"
            ) |
            {head_branch, cancel_url}
          ' |
          jq --arg head_branch "${BRANCH}"
          'select(.head_branch == $head_branch) | .cancel_url' |
          jq --join-output --slurp 'join("\u0000")' |
          xargs --max-args=1 --max-procs=2 --no-run-if-empty --null --verbose --
          gh api -X POST || true;
          gh api "repos/${REPO}/actions/runs" --paginate -q '
            .workflow_runs[] |
            select(
              .conclusion != null and
              .status != "in_progress" and
              .head_branch != "stable"
            ) |
            {head_branch, url}
          ' |
          jq --arg head_branch "${BRANCH}"
          'select(.head_branch == $head_branch) | .url' |
          jq --join-output --slurp 'join("\u0000")' |
          xargs --max-args=1 --max-procs=2 --no-run-if-empty --null --verbose --
          gh api -X DELETE
  cleanup-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          filter: tree:0
      - env:
          BRANCH: ${{ github.event.ref }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        name: Cleanup
        run: >
          gh extension install actions/gh-actions-cache;
          gh actions-cache list -R "${REPO}" -B "${BRANCH}" | cut -f 1 |
          xargs --max-args=1 --max-procs=2 --no-run-if-empty --verbose --
          gh actions-cache delete -R "${REPO}" -B "${BRANCH}" --confirm

name: cleanup by branch on delete

# yamllint disable-line rule:truthy
on:
  delete: ~
