---
jobs:
  cleanup-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - env:
          BRANCH: ${{ github.ref_name }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        name: Cleanup
        run: >
          gh extension install actions/gh-actions-cache;
          gh actions-cache list -R "${REPO}" -B "${BRANCH}" | cut -f 1 |
          xargs --max-args=1 --max-procs=2 --no-run-if-empty --verbose --
          gh actions-cache delete -R "${REPO}" -B "${BRANCH}" --confirm
  cleanup-packages:
    permissions:
      actions: write
    runs-on: ubuntu-22.04
    steps:
      - env:
          BRANCH: ${{ github.ref_name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        name: Cleanup
        run: >
          set -o pipefail;
          gh api "repos/${REPO}/actions/runs" --paginate -q '
            .workflow_runs |
            map(
              select(
                .conclusion != null and
                .status != "in_progress" and
                .head_branch != "stable"
              )
            )[]
          ' | jq -js --arg head_branch "${BRANCH}"
          'map(select(.head_branch == $head_branch) | .url) | join("\u0000")' |
          xargs --max-args=1 --max-procs=2 --no-run-if-empty --null --verbose --
          gh api -X DELETE

name: cleanup by branch on delete

# yamllint disable-line rule:truthy
on:
  branch:
    types:
      - deleted
