---
env:
  CC: /usr/local/bin/clang
  CMAKE_EXPORT_COMPILE_COMMANDS: "YES"
  CXX: /usr/local/bin/clang++

jobs:
  clangformat:
    concurrency:
      cancel-in-progress: ${{ github.ref != 'refs/heads/stable' }}
      group: clangformat-${{ github.ref }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Lint c++ code
        uses: ./
        with:
          run: >
            tools/g-ls-tree.sh '(' -name '*.cpp' -or -name '*.h' -or -name '*.hpp' ')' |
            xargs --no-run-if-empty --null --
            /usr/local/bin/clang-format --dry-run -style=file -Werror
  clangtidy:
    concurrency:
      cancel-in-progress: ${{ github.ref != 'refs/heads/stable' }}
      group: clangtidy-${{ github.ref }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.1.0
        with:
          submodules: true
      - name: Cache
        uses: actions/cache@v3.0.11
        with:
          key: clang-tidy-${{ hashFiles('CMakeLists.txt') }}-v1
          path: build
      - uses: ./
        with:
          run: sudo python3 tools/llvm.py
      - env:
          CC: /usr/bin/clang-${{ env.CLANG_VERSION }}
          CXX: /usr/bin/clang++-${{ env.CLANG_VERSION }}
        name: Configure CMake
        uses: ./
        with:
          run: cmake -B build -S .
      - if: ${{ !matrix.lints }}
        name: Lint c++ code
        uses: ./
        with:
          run: >
          python3 tools/clang_tidy.py build
          bugprone-*,bugprone-use-after-move,-bugprone-easily-swappable-parameters,-bugprone-exception-escape
          cert-*
          clang-*
          concurrency-*
          cppcoreguidelines-*
          hicpp-*,hicpp-invalid-access-moved
          misc-*,misc-const-correctness,-misc-confusable-identifiers,-misc-no-recursion
          misc-confusable-identifiers
          modernize-*
          performance-*
          portability-*
          readability-*,-readability-identifier-length,-readability-static-accessed-through-instance

name: ClangTidy

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - stable
    paths:
      - .github/workflows/clang-tidy.yml
      - "**.cpp"
      - "**.hpp"
      - "**.h"
      - .clang-format
      - .clang-tidy
      - CMakeLists.txt
  push:
    branches:
      - stable
    paths:
      - .github/workflows/clang-tidy.yml
      - "**.cpp"
      - "**.hpp"
      - "**.h"
      - .clang-format
      - .clang-tidy
      - CMakeLists.txt
  workflow_dispatch: ~
