---
env:
  CLANG_VERSION: "15"
  CMAKE_EXPORT_COMPILE_COMMANDS: "YES"

jobs:
  clangformat:
    concurrency:
      cancel-in-progress: true
      group: clangformat-${{ github.workflow }}-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DoozyX/clang-format-lint-action@v0.14
        with:
          clangFormatVersion: 14
          extensions: cpp,h,hpp
  clangtidy:
    concurrency:
      cancel-in-progress: true
      group: clangtidy-${{ matrix.lints }}-${{ github.workflow }}-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh && sudo ./llvm.sh ${{env.CLANG_VERSION}} all && rm -rf llvm.sh
      - name: Configure CMake
        run: CC=/usr/bin/clang-${{env.CLANG_VERSION}} CXX=/usr/bin/clang++-${{env.CLANG_VERSION}} cmake -B build
        working-directory: ${{github.workspace}}
      - if: ${{ matrix.lints }}
        name: Lint c++ code
        run: find . -name '*.cpp' -print0 | xargs -0 -- git ls-tree --full-tree --name-only -z HEAD -- | xargs -0 -- clang-tidy-${{env.CLANG_VERSION}} -p=build -checks=-*,${{matrix.lints}}
        working-directory: ${{github.workspace}}
      - if: ${{ !matrix.lints }}
        name: Lint c++ code
        run: find . -name '*.cpp' -print0 | xargs -0 -- git ls-tree --full-tree --name-only -z HEAD -- | xargs -0 -- clang-tidy-${{ env.CLANG_VERSION }} -p=build
        working-directory: ${{ github.workspace }}
    strategy:
      matrix:
        lints:
          - false
          - bugprone-*,-bugprone-easily-swappable-parameters,-bugprone-exception-escape
          - cert-*
          - clang-*
          - concurrency-*
          - cppcoreguidelines-*
          - hicpp-*
          - misc-*,-misc-confusable-identifiers,-misc-no-recursion
          - misc-confusable-identifiers
          - modernize-*
          - performance-*
          - portability-*
          - readability-*,-readability-identifier-length,-readability-static-accessed-through-instance

name: ClangTidy

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - stable
    paths:
      - .github/workflows/**
      - "**.cpp"
      - "**.hpp"
      - "**.h"
      - .clang-format
      - .clang-tidy
      - CMakeLists.txt
  push:
    branches:
      - stable
    paths:
      - .github/workflows/**
      - "**.cpp"
      - "**.hpp"
      - "**.h"
      - .clang-format
      - .clang-tidy
      - CMakeLists.txt
  workflow_dispatch: ~
