name: ClangFormat

on:
  push:
    branches: [stable]
    paths:
      - ".github/workflows/**"
      - "**.cpp"
      - "**.hpp"
      - "**.h"
      - CMakeLists.txt
  pull_request:
    branches: [stable]
    paths:
      - ".github/workflows/**"
      - "**.cpp"
      - "**.hpp"
      - "**.h"
      - CMakeLists.txt
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DoozyX/clang-format-lint-action@v0.14
        with:
          extensions: "cpp,h,hpp"
          clangFormatVersion: 14
