---
env:
  CC: /usr/local/bin/clang
  CMAKE_EXPORT_COMPILE_COMMANDS: "YES"
  CXX: /usr/local/bin/clang++

jobs:
  clangformat:
    concurrency:
      cancel-in-progress: ${{ github.ref != 'refs/heads/stable' }}
      group: ${{ github.workflow }}-${{ github.ref }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Lint c++ code
        uses: ./
        with:
          run: >
            tools/g-ls-tree.sh '(' -name '*.cpp' -or -name '*.h' -or -name '*.hpp' ')' |
            xargs --no-run-if-empty --null --
            /usr/local/bin/clang-format --dry-run -style=file -Werror
  clangtidy:
    concurrency:
      cancel-in-progress: ${{ github.ref != 'refs/heads/stable' }}
      group: ${{ matrix.lints }}-${{ github.workflow }}-${{ github.ref }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.1.0
        with:
          submodules: true
      - name: CCache
        uses: actions/cache@v3.0.11
        with:
          key: ccache
          path: .ccache
      - name: Configure CMake
        uses: ./
        with:
          run: cmake -B build -S .
      - if: matrix.lints
        name: Lint c++ code
        uses: ./
        with:
          run: >
            tools/g-ls-tree.sh -name '*.cpp' |
            xargs --no-run-if-empty --null --
            /usr/local/bin/clang-tidy -p=build -checks=-*,${{ matrix.lints }}
      - if: ${{ !matrix.lints }}
        name: Lint c++ code
        uses: ./
        with:
          run: >
            tools/g-ls-tree.sh -name '*.cpp' |
            xargs --no-run-if-empty --null --
            /usr/local/bin/clang-tidy -p=build
    strategy:
      matrix:
        lints:
          - false
          - bugprone-*,bugprone-use-after-move,-bugprone-easily-swappable-parameters,-bugprone-exception-escape
          - cert-*
          - clang-*
          - concurrency-*
          - cppcoreguidelines-*
          - hicpp-*,hicpp-invalid-access-moved
          - misc-*,misc-const-correctness,-misc-confusable-identifiers,-misc-no-recursion
          - misc-confusable-identifiers
          - modernize-*
          - performance-*
          - portability-*
          - readability-*,-readability-identifier-length,-readability-static-accessed-through-instance

name: ClangTidy

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - stable
    paths:
      - .github/workflows/clang-tidy.yml
      - "**.cpp"
      - "**.hpp"
      - "**.h"
      - .clang-format
      - .clang-tidy
      - CMakeLists.txt
  push:
    branches:
      - stable
    paths:
      - .github/workflows/clang-tidy.yml
      - "**.cpp"
      - "**.hpp"
      - "**.h"
      - .clang-format
      - .clang-tidy
      - CMakeLists.txt
  workflow_dispatch: ~
