---
jobs:
  clangformat:
    concurrency:
      cancel-in-progress: ${{ github.ref != 'refs/heads/stable' }}
      group: ${{ github.workflow }}-${{ github.ref }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Lint c++ code
        uses: ./
        with:
          run: >
            python tools/g_ls_tree.py cpp h hpp |
            xargs --no-run-if-empty --null --
            clang-format --dry-run -style=file -Werror

name: ClangFormat

# yamllint disable-line rule:truthy
on:
  pull_request:
    paths: &paths
      - .clang-format
      - .github/workflows/clang-format.yml
      - "**.cpp"
      - "**.h"
      - "**.hpp"
      - action.yml
      - requirements.core.txt
      - requirements.txt
      - tools/action.py
      - tools/asyncio_as_completed.py
      - tools/asyncio_cmd.py
      - tools/g_ls_tree.py
  push:
    branches:
      - stable
    paths: *paths
  workflow_dispatch: ~
