---
jobs:
  clangtidy:
    concurrency:
      cancel-in-progress: ${{ github.ref != 'refs/heads/stable' }}
      group: ${{ github.workflow }}-${{ github.ref }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.2.0
        with:
          submodules: true
      - name: CCache
        uses: actions/cache@v3.2.1
        with:
          key: clang-tidy-${{ github.run_id }}
          path: .ccache
          restore-keys: build-
      - name: Configure CMake
        uses: ./
        with:
          run: cmake -B build -S .
      - name: Lint c++ code
        uses: ./
        with:
          run: >
            python tools/clang_tidy.py build
            bugprone-*,bugprone-use-after-move,-bugprone-easily-swappable-parameters,-bugprone-exception-escape
            cert-*
            clang-*
            concurrency-*
            cppcoreguidelines-*
            hicpp-*,hicpp-invalid-access-moved
            misc-*,misc-const-correctness,-misc-confusable-identifiers,-misc-no-recursion
            misc-confusable-identifiers
            modernize-*
            performance-*
            portability-*
            readability-*,-readability-identifier-length,-readability-static-accessed-through-instance

name: ClangTidy

# yamllint disable-line rule:truthy
on:
  pull_request:
    paths:
      - .clang-tidy
      - .github/workflows/clang-tidy.yml
      - "**.cpp"
      - "**.h"
      - "**.hpp"
      - action.yml
      - CMakeLists.txt
      - requirements.txt
      - tools/action.py
      - tools/asyncio_cmd.py
      - tools/g_ls_tree.py
  push:
    branches:
      - stable
    paths:
      - .clang-tidy
      - .github/workflows/clang-tidy.yml
      - "**.cpp"
      - "**.h"
      - "**.hpp"
      - action.yml
      - CMakeLists.txt
      - requirements.txt
      - tools/action.py
      - tools/asyncio_cmd.py
      - tools/g_ls_tree.py
  workflow_dispatch: ~
