name: ClangFormat

on:
  push:
    branches: [stable]
    paths:
      - '.github/workflows/**'
      - '**.cpp'
      - '**.hpp'
      - '**.h'
      - CMakeLists.txt
  pull_request:
    branches: [stable]
  workflow_dispatch:

env:
  CLANG_VERSION: 15
  CMAKE_EXPORT_COMPILE_COMMANDS: YES

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh && sudo ./llvm.sh ${{env.CLANG_VERSION}} all && rm -rf llvm.sh
      - name: Configure CMake
        working-directory: ${{github.workspace}}
        run: CC=/usr/bin/clang-${{env.CLANG_VERSION}} CXX=/usr/bin/clang++-${{env.CLANG_VERSION}} cmake -B build
      - name: Lint c++ code
        working-directory: ${{github.workspace}}
        run: find . '(' -name '*.cpp' -or -name '*.h' -or -name '*.hpp' ')' -print0 | xargs -0 -- git ls-tree --full-tree --name-only -z HEAD -- | xargs -0 -- clang-format-${{env.CLANG_VERSION}} -style=file -Werror
