---
jobs:
  corpus-retest:
    concurrency:
      cancel-in-progress: ${{ github.ref != 'refs/heads/stable' }}
      group: corpus-${{ github.workflow }}-${{ github.ref }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
          submodules: true
      - env:
          GITHUB_REF: ${{ github.ref }}
        name: Corpus recheck
        uses: ./
        with:
          run: |
            rustup default stable
            python tools/crash_reset.py
            python tools/corpus_gather.py "${GITHUB_REF}"
            python tools/corpus_retest.py build
      - if: github.ref == 'refs/heads/stable'
        name: Run corpus
        uses: ./
        with:
          run: |
            python tools/ninja.py build corpus
            python tools/corpus_retest.py build
      - name: Corpus baseline
        uses: ./
        with:
          run: |
            git restore --source origin/stable --staged unit_tests/fuzz/corpus
            git restore --worktree unit_tests/fuzz/corpus
            python tools/corpus_trim.py
      - continue-on-error: true
        uses: stefanzweifel/git-auto-commit-action@v5.0.0
        with:
          branch: corpus-${{ github.run_id }}-retest
          commit_message: Update fuzzing corpus.
          create_branch: true
          file_pattern: unit_tests/fuzz
          repository: ${{ github.workspace }}
  debug:
    concurrency:
      cancel-in-progress: ${{ github.ref != 'refs/heads/stable' }}
      group: debug-${{ github.workflow }}-${{ github.ref }}
    env:
      CXXFLAGS: -O0 -g -pedantic -DDEBUG -Wall -Wdeprecated -Werror -Wextra -Wpedantic
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          filter: tree:0
          submodules: true
      - name: Run tests
        uses: ./
        with:
          run: |
            rustup default stable
            python tools/cmake_ninja.py
  libcpp:
    concurrency:
      cancel-in-progress: ${{ github.ref != 'refs/heads/stable' }}
      group: libcpp-${{ github.workflow }}-${{ github.ref }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          filter: tree:0
          submodules: true
      - env:
          CMAKE_BUILD_TYPE: RelWithDebInfo
          CXXFLAGS: -stdlib=libc++
        name: Basic unit tests
        uses: ./
        with:
          run: |
            rustup default stable
            python tools/cmake_ninja.py
  release:
    concurrency:
      cancel-in-progress: ${{ github.ref != 'refs/heads/stable' }}
      group: release-${{ github.workflow }}-${{ github.ref }}
    env:
      CMAKE_BUILD_TYPE: Release
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          filter: tree:0
          submodules: true
      - name: Run tests
        uses: ./
        with:
          run: |
            rustup default stable
            python tools/cmake_ninja.py

name: CMake

# yamllint disable-line rule:truthy
on:
  push:
    paths:
      - .github/workflows/cmake.yml
      - "**.cpp"
      - "**.h"
      - "**.hpp"
      - "**.py"
      - action.yml
      - cmake/**
      - CMakeLists.txt
      - external/**
      - oxidation/**
      - requirements.txt
      - tools/requirements.txt
      - unit_tests/fuzz/cases.json
  workflow_dispatch: ~
