---
jobs:
  corpus:
    concurrency:
      cancel-in-progress: ${{ github.ref != 'refs/heads/stable' }}
      group: corpus-${{ github.workflow }}-${{ github.ref }}
    env:
      CXXFLAGS: ""
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.2.0
        with:
          submodules: true
      - name: CCache
        uses: actions/cache@v3.0.11
        with:
          key: build-${{ hashFiles('CMakeLists.txt') }}-${{ github.run_id }}
          path: .ccache
          restore-keys: |
            build-${{ hashFiles('CMakeLists.txt') }}
            build
      - name: Run regression
        uses: ./
        with:
          run: |
            python tools/before.py
            cmake -GNinja -B build -S .
            python tools/ninja.py build check-rand regression
      - if: github.ref == 'refs/heads/stable'
        name: Run corpus
        uses: ./
        with:
          run: |
            python tools/ninja.py build -k0 corpus || true
            git config --global user.email email
            git config --global user.name name
            python tools/corpus_gather.py
      - name: Corpus trim
        uses: ./
        with:
          run: |
            python tools/corpus_trim.py
            set +e
            for opt in --global --local --system --worktree; do
              git config "${opt}" --unset-all user.email
              git config "${opt}" --unset-all user.name
            done
            exit 0
      - continue-on-error: ${{ github.ref != 'refs/heads/stable' }}
        uses: stefanzweifel/git-auto-commit-action@v4.16.0
        with:
          branch: regression-${{ github.workflow }}-${{ github.ref }}/${{ github.run_id }}
          commit_message: Update fuzzing corpus.
          create_branch: true
          file_pattern: unit_tests/fuzz
          repository: ${{ github.workspace }}
  debug:
    concurrency:
      cancel-in-progress: ${{ github.ref != 'refs/heads/stable' }}
      group: debug-${{ github.workflow }}-${{ github.ref }}
    env:
      CMAKE_BUILD_TYPE: Debug
      CXXFLAGS: "-Wall -Werror -Wpedantic"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.2.0
        with:
          submodules: true
      - name: CCache
        uses: actions/cache@v3.0.11
        with:
          key: debug-${{ github.run_id }}
          path: .ccache
          restore-keys: |
            debug-
            build-
      - name: Run regression
        uses: ./
        with:
          run: |
            python tools/before.py
            cmake -GNinja -B build -S .
            python tools/ninja.py build check-rand regression
  regression:
    concurrency:
      cancel-in-progress: ${{ github.ref != 'refs/heads/stable' }}
      group: regression-${{ github.workflow }}-${{ github.ref }}
    runs-on: ubuntu-22.04
    env:
      CXXFLAGS: ""
    steps:
      - uses: actions/checkout@v3.2.0
        with:
          submodules: true
      - name: CCache
        uses: actions/cache@v3.0.11
        with:
          key: build-${{ github.run_id }}
          path: .ccache
          restore-keys: |
            build-${{ hashFiles('CMakeLists.txt') }}
            build
      - name: Build fuzzers
        uses: ./
        with:
          run: |
            cmake -GNinja -B build -S .
            ninja -C build -j1 fuzzers
      - name: Corpus regression
        uses: ./
        with:
          run: |
            python tools/before.py
            python tools/corpus_regression.py
      - continue-on-error: ${{ github.ref != 'refs/heads/stable' }}
        uses: stefanzweifel/git-auto-commit-action@v4.16.0
        with:
          branch: update-fuzz-${{ github.ref }}/${{ github.run_id }}
          commit_message: Update fuzzing corpus.
          create_branch: true
          file_pattern: unit_tests/fuzz
          repository: ${{ github.workspace }}
  release:
    concurrency:
      cancel-in-progress: ${{ github.ref != 'refs/heads/stable' }}
      group: release-${{ github.workflow }}-${{ github.ref }}
    env:
      CMAKE_BUILD_TYPE: Release
      CXXFLAGS: ""
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.2.0
        with:
          submodules: true
      - name: CCache
        uses: actions/cache@v3.0.11
        with:
          key: release-${{ github.run_id }}
          path: .ccache
          restore-keys: |
            release-
            build-
      - name: Run regression
        uses: ./
        with:
          run: |
            python tools/before.py
            cmake -GNinja -B build -S .
            python tools/ninja.py build check-rand regression
  scan-build:
    concurrency:
      cancel-in-progress: ${{ github.ref != 'refs/heads/stable' }}
      group: scan-build-${{ github.workflow }}-${{ github.ref }}
    env:
      CXXFLAGS: ""
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.2.0
        with:
          submodules: true
      - name: Scan Build
        uses: ./
        with:
          run: >
            scan-build
            bash -c '
              set -e -o pipefail
              cmake -GNinja -B build -S .
              python tools/ninja.py build
            '
            ! find /tmp -type d -name 'scan-build-*'

name: CMake

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - stable
    paths-ignore:
      - .dockerignore
      - .github/workflows/docker.yml
      - "**.md"
      - Dockerfile*
      - tools/boot.yml
      - tools/devcontainer.yml
      - unit_tests/fuzz/corpus/*
      - unit_tests/fuzz/crashes/*
  push:
    branches:
      - stable
    paths-ignore:
      - .dockerignore
      - .github/workflows/docker.yml
      - "**.md"
      - Dockerfile*
      - tools/boot.yml
      - tools/devcontainer.yml
      - unit_tests/fuzz/corpus/*
      - unit_tests/fuzz/crashes/*
  workflow_dispatch: ~
