---
env:
  BUILD_TYPE: Release
  CLANG_VERSION: 15

jobs:
  cmake:
    concurrency:
      cancel-in-progress: ${{ github.ref != 'refs/heads/stable' }}
      group: ${{ matrix.targets }}-${{ github.workflow }}-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Cache
        uses: actions/cache@v3.0.7
        with:
          key: build
          path: build
          restore-keys: build
          upload-chunk-size: 4000000
      - run: >
          wget https://apt.llvm.org/llvm.sh &&
          chmod +x llvm.sh &&
          sudo ./llvm.sh ${{ env.CLANG_VERSION }} &&
          rm -rf llvm.sh
      - env:
          CC: /usr/bin/clang-${{ env.CLANG_VERSION }}
          CMAKE_BUILD_TYPE: ${{ env.BUILD_TYPE }}
          CXX: /usr/bin/clang++-${{ env.CLANG_VERSION }}
        name: Configure CMake
        run: cmake -B build -S .
        working-directory: ${{ github.workspace }}
      - if: matrix.targets == 'check'
        name: Build dev tools
        run: make
        working-directory: ${{ github.workspace }}/build
      - continue-on-error: >
          ${{ github.ref == 'refs/heads/stable' &&
              matrix.targets != 'check' &&
              matrix.targets != 'check_rand' }}
        name: Test
        run: make ${{ matrix.targets }}
        working-directory: ${{ github.workspace }}/build
      - if: github.ref == 'refs/heads/stable'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: ${{ hashFiles('unit_tests/fuzz/corpus/*') }}
          commit_message: Update fuzzing corpus.
          create_branch: true
          file_pattern: unit_tests/fuzz/corpus/*
          repository: ${{ github.workspace }}
    strategy:
      fail-fast: false
      matrix:
        targets:
          - check
          - check_rand
          - corpus
          - corpus-ellipsis
          - corpus-false
          - corpus-keywords
          - corpus-name
          - corpus-none
          - corpus-number
          - corpus-string
          - corpus-true

name: CMake

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - stable
  push:
    branches:
      - stable
  workflow_dispatch: ~
