---
jobs:
  cmakelint:
    concurrency:
      cancel-in-progress: ${{ github.ref != 'refs/heads/stable' }}
      group: ${{ github.workflow }}-${{ github.ref }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Lint CMakeLists.txt
        uses: ./
        with:
          run: cmakelint

name: Cmake Lint

# yamllint disable-line rule:truthy
on:
  pull_request:
    paths:
      - .cmakelintrc
      - .github/workflows/cmakelint.yml
      - action.yml
      - cmake/**
      - CMakeLists.txt
      - requirements.txt
      - tools/action.py
      - tools/asyncio_cmd.py
  push:
    branches:
      - stable
    paths:
      - .cmakelintrc
      - .github/workflows/cmakelint.yml
      - action.yml
      - cmake/**
      - CMakeLists.txt
      - requirements.txt
      - tools/action.py
      - tools/asyncio_cmd.py
  workflow_dispatch: ~
