---
env:
  CLANG_VERSION: 15
  CMAKE_BUILD_TYPE: Debug
  CXXFLAGS: >
    -DCHIMERA_PATH="${{ github.workspace }}/stdlib"
    -fsanitize-coverage=no-prune
    -fsanitize-coverage=trace-cmp
    -fsanitize-coverage=trace-div
    -fsanitize-coverage=trace-gep
    -fsanitize-coverage=trace-loads
    -fsanitize-coverage=trace-stores

jobs:
  regression:
    concurrency:
      cancel-in-progress: ${{ github.ref != 'refs/heads/stable' }}
      group: regression-${{ github.workflow }}-${{ github.ref }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.1.0
        with:
          submodules: true
      - name: Cache cmake
        uses: actions/cache@v3.0.10
        with:
          key: build-${{ hashFiles('CMakeLists.txt') }}-${{ env.CLANG_VERSION }}-v2
          path: build
      - name: Cache python
        uses: actions/cache@v3.0.10
        with:
          key: python3-${{ hashFiles('requirements.txt') }}
          path: env
      - run: >
          wget https://apt.llvm.org/llvm.sh &&
          chmod +x llvm.sh &&
          sudo ./llvm.sh ${{ env.CLANG_VERSION }} all &&
          rm -rf llvm.sh &&
          sudo apt-get install -y ninja-build
      - name: Build python tools
        run: >
          python3 -m venv --upgrade --upgrade-deps env &&
          env/bin/pip3 install --upgrade pip setuptools wheel &&
          env/bin/pip3 install -r requirements.txt
        working-directory: ${{ github.workspace }}
      - env:
          CC: /usr/bin/clang-${{ env.CLANG_VERSION }}
          CXX: /usr/bin/clang++-${{ env.CLANG_VERSION }}
        name: Configure CMake
        run: >
          git -C external/Catch/ apply ${{ github.workspace }}/patches/Catch &&
          cmake -GNinja -B build -S .
        working-directory: ${{ github.workspace }}
      - name: Run regression
        run: >
          ninja -j1 chimera_grammar &&
          ninja -j2 chimera unit_test &&
          ninja &&
          ninja regression
        working-directory: ${{ github.workspace }}/build
      - continue-on-error: true
        run: ninja -k0 corpus
        working-directory: ${{ github.workspace }}/build
      - if: github.ref != 'refs/heads/stable'
        run: env/bin/python3 tools/corpus_trim.py
        working-directory: ${{ github.workspace }}
      - if: github.ref == 'refs/heads/stable'
        run: >
          git config --global user.email email &&
          git config --global user.name name &&
          env/bin/python3 tools/corpus.py
        working-directory: ${{ github.workspace }}
      - continue-on-error: true
        run: |
          for opt in --global --local --system --worktree; do
            git config "${opt}" --unset-all user.email
            git config "${opt}" --unset-all user.name
          done
        working-directory: ${{ github.workspace }}
      - uses: stefanzweifel/git-auto-commit-action@v4.15.1
        with:
          # yamllint disable-line rule:line-length
          branch: regression-${{ github.workflow }}-${{ github.ref }}/${{ github.run_id }}
          commit_message: Update fuzzing corpus.
          create_branch: true
          file_pattern: unit_tests/fuzz
          repository: ${{ github.workspace }}
  scan-build:
    concurrency:
      cancel-in-progress: ${{ github.ref != 'refs/heads/stable' }}
      group: scan-build-${{ github.workflow }}-${{ github.ref }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.1.0
        with:
          submodules: true
      - run: >
          wget https://apt.llvm.org/llvm.sh &&
          chmod +x llvm.sh &&
          sudo ./llvm.sh ${{ env.CLANG_VERSION }} all &&
          rm -rf llvm.sh &&
          sudo apt-get install -y ninja-build
      - name: Scan Build
        run: >
          git -C external/Catch/ apply ${{ github.workspace }}/patches/Catch &&
          CXXFLAGS=''
          scan-build-${{ env.CLANG_VERSION }}
          --use-cc /usr/bin/clang-${{ env.CLANG_VERSION }}
          --use-c++ /usr/bin/clang++-${{ env.CLANG_VERSION }}
          bash -c '
            cmake -GNinja -B build -S . &&
            cd build &&
            ninja -j1 chimera_grammar &&
            ninja -j2 chimera fuzzers &&
            ninja &&
            ninja regression
          '
        working-directory: ${{ github.workspace }}

name: CMake

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - stable
    paths-ignore:
      - .dockerignore
      - "**.md"
      - Dockerfile
      - tools/docker.sh
      - unit_tests/fuzz/corpus/*
      - unit_tests/fuzz/crashes/*
  push:
    branches:
      - stable
    paths-ignore:
      - .dockerignore
      - "**.md"
      - Dockerfile
      - tools/docker.sh
      - unit_tests/fuzz/corpus/*
      - unit_tests/fuzz/crashes/*
  workflow_dispatch: ~
