---
env:
  CLANG_VERSION: 15
  CMAKE_BUILD_TYPE: Debug
  CXXFLAGS: -DNDEBUG -DCHIMERA_PATH

jobs:
  cmake:
    concurrency:
      cancel-in-progress: ${{ github.ref != 'refs/heads/stable' }}
      group: ${{ matrix.targets }}-${{ github.workflow }}-${{ github.ref }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.0.2
        with:
          submodules: true
      - if: matrix.targets != 'scan-build'
        name: Cache
        uses: actions/cache@v3.0.8
        with:
          # yamllint disable-line rule:line-length
          key: ${{ hashFiles('CMakeLists.txt') }}-${{ env.CLANG_VERSION }}-${{ env.CMAKE_BUILD_TYPE }}-${{ env.CXXFLAGS }}
          path: build
      - run: >
          wget https://apt.llvm.org/llvm.sh &&
          chmod +x llvm.sh &&
          sudo ./llvm.sh ${{ env.CLANG_VERSION }} all &&
          rm -rf llvm.sh &&
          sudo apt-get install -y ninja-build
      - env:
          CC: /usr/bin/clang-${{ env.CLANG_VERSION }}
          CXX: /usr/bin/clang++-${{ env.CLANG_VERSION }}
        if: matrix.targets != 'scan-build'
        name: Configure CMake
        run: >
          git -C external/Catch/ apply ${{ github.workspace }}/patches/Catch &&
          cmake -GNinja -B build -S .
        working-directory: ${{ github.workspace }}
      - if: matrix.targets == 'scan-build'
        name: Scan Build
        run: >
          git -C external/Catch/ apply ${{ github.workspace }}/patches/Catch &&
          scan-build-${{ env.CLANG_VERSION }}
          --use-cc /usr/bin/clang-${{ env.CLANG_VERSION }}
          --use-c++ /usr/bin/clang++-${{ env.CLANG_VERSION }}
          bash -c '
            cmake -DCMAKE_BUILD_TYPE=Debug -GNinja -B build -S . &&
            ninja -C build unit_test
          '
        working-directory: ${{ github.workspace }}
      - if: matrix.targets != 'scan-build'
        name: Build dev tools
        run: ninja
        working-directory: ${{ github.workspace }}/build
      - name: Run base unit_test
        run: ninja check
        working-directory: ${{ github.workspace }}/build
      - continue-on-error: ${{ startsWith(matrix.targets, 'corpus-') }}
        if: matrix.targets != 'scan-build'
        name: Test
        run: ninja ${{ matrix.targets }}
        working-directory: ${{ github.workspace }}/build
      - run: tools/corpus_trim.sh
        working-directory: ${{ github.workspace }}
      - uses: stefanzweifel/git-auto-commit-action@v4.14.1
        with:
          # yamllint disable-line rule:line-length
          branch: ${{ matrix.targets }}-${{ github.workflow }}-${{ github.ref }}/${{ github.run_id }}
          commit_message: Update fuzzing corpus.
          create_branch: true
          file_pattern: unit_tests/fuzz
          repository: ${{ github.workspace }}
    strategy:
      fail-fast: false
      matrix:
        targets:
          - check_rand
          - corpus-ellipsis
          - corpus-false
          - corpus-keywords
          - corpus-name
          - corpus-none
          - corpus-number
          - corpus-string
          - corpus-true
          - corpus-vm
          - scan-build

name: CMake

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - stable
    paths-ignore:
      - .dockerignore
      - "**.md"
      - Dockerfile
      - tools/docker.sh
      - unit_tests/fuzz/corpus/*
      - unit_tests/fuzz/crashes/*
  push:
    branches:
      - stable
    paths-ignore:
      - .dockerignore
      - "**.md"
      - Dockerfile
      - tools/docker.sh
      - unit_tests/fuzz/corpus/*
      - unit_tests/fuzz/crashes/*
  workflow_dispatch: ~
