---
jobs:
  cmakelint:
    concurrency:
      cancel-in-progress: ${{ github.ref != 'refs/heads/stable' }}
      group: ${{ github.workflow }}-${{ github.ref }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Lint CMakeList.txt
        uses: ./
        with:
          run: |
            python tools/before.py
            cmakelint

name: Cmake Lint

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - stable
    paths:
      - .github/workflows/cmakelint.yml
      - cmake/**
      - CMakeList.txt
      - requirements.txt
  push:
    branches:
      - stable
    paths:
      - .github/workflows/cmakelint.yml
      - cmake/**
      - CMakeList.txt
      - requirements.txt
  workflow_dispatch: ~
