---
env:
  CPPFLAGS: -DCHIMERA_PATH="/github/workspace/stdlib"
jobs:
  corpus-merge:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.0
        with:
          submodules: true
      - name: CCache
        uses: actions/cache@v3.3.2
        with:
          key: merge-${{ github.run_id }}
          path: .ccache
          restore-keys: corpus-
      - name: Build project
        uses: ./
        with:
          run: |
            rustup default stable
            cmake -GNinja -B build -S .
            python tools/ninja.py build fuzzers
            ccache --cleanup
            ccache --trim-dir .ccache/remote --trim-max-size 600Mi
      - name: Corpus merge
        uses: ./
        with:
          run: |
            python tools/corpus_merge.py
            BASE_REF=HEAD python tools/corpus_freeze.py unit_tests/fuzz/cases.json
      - uses: stefanzweifel/git-auto-commit-action@v4.16.0
        with:
          branch: corpus-${{ github.run_id }}
          commit_message: Update fuzzing corpus.
          create_branch: true
          file_pattern: unit_tests/fuzz/corpus
          repository: ${{ github.workspace }}
name: Corpus Merge
# yamllint disable-line rule:truthy
on:
  workflow_dispatch: ~
