---
env:
  IMAGE: ghcr.io/asakatida/chimera
jobs:
  docker:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.workflow }}-${{ github.ref }}
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: docker://hadolint/hadolint:2.12.0
        with:
          args: --verbose Dockerfile
          entrypoint: /bin/hadolint
      - uses: docker://hadolint/hadolint:2.12.0
        with:
          args: --verbose Dockerfile.python
          entrypoint: /bin/hadolint
      - uses: docker/setup-qemu-action@v2.1.0
      - uses: docker/setup-buildx-action@v2.5.0
      - uses: docker/login-action@v2.1.0
        with:
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          username: ${{ github.actor }}
      - uses: docker/build-push-action@v4.0.0
        with:
          file: Dockerfile.python
          push: true
          tags: ${{ env.IMAGE }}:python3.12
      - uses: docker/build-push-action@v4.0.0
        with:
          push: true
          tags: ${{ env.IMAGE }}-testing:${{ github.sha }}
name: Docker
# yamllint disable-line rule:truthy
on:
  pull_request:
    paths:
      - .dockerignore
      - .github/workflows/docker.yml
      - Dockerfile*
      - requirements.core.txt
      - requirements.txt
      - tools/boot.yml
  workflow_dispatch: ~
