---
jobs:
  docker:
    concurrency:
      cancel-in-progress: ${{ github.ref != 'refs/heads/stable' }}
      group: ${{ github.workflow }}-${{ github.ref }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.2.0
      - uses: docker://hadolint/hadolint:2.12.0
        with:
          args: --verbose Dockerfile
          entrypoint: /bin/hadolint
      - uses: docker://hadolint/hadolint:2.12.0
        with:
          args: --verbose Dockerfile.python
          entrypoint: /bin/hadolint
      - uses: docker/setup-qemu-action@v2.1.0
      - uses: docker/setup-buildx-action@v2.2.1
      - if: ${{ github.ref == 'refs/heads/stable' }}
        uses: docker/login-action@v2.1.0
        with:
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
      - continue-on-error: true
        uses: docker/build-push-action@v3.2.0
        with:
          file: Dockerfile.python
          push: ${{ github.ref == 'refs/heads/stable' }}
          tags: asakatida/python:3.12
      - uses: docker/build-push-action@v3.2.0
        with:
          push: ${{ github.ref == 'refs/heads/stable' }}
          tags: asakatida/chimera:latest
name: Docker
# yamllint disable-line rule:truthy
on:
  pull_request:
    paths:
      - .dockerignore
      - .github/workflows/docker.yml
      - Dockerfile*
      - requirements.txt
      - tools/boot.yml
  push:
    branches:
      - stable
    paths:
      - .dockerignore
      - .github/workflows/docker.yml
      - Dockerfile*
      - requirements.txt
      - tools/boot.yml
  schedule:
    - cron: 20 14 * * *
  workflow_dispatch: ~
