---
jobs:
  docker:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.workflow }}-${{ github.ref }}
    runs-on: ubuntu-22.04
    steps:
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
      - uses: docker/build-push-action@v3
        with:
          push: ${{ github.ref == 'refs/heads/stable' }}
          tags: asakatida/chimera:latest
name: Docker
# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - stable
    paths:
      - .dockerignore
      - .github/workflows/docker.yml
      - Dockerfile
      - tools/docker.sh
  push:
    branches:
      - stable
    paths:
      - .dockerignore
      - .github/workflows/docker.yml
      - Dockerfile
      - tools/docker.sh
