name: ISort

on:
  push:
    branches: [stable]
    paths:
      - '.github/workflows/**'
      - '**.py'
      - requirements.txt
  pull_request:
    branches: [stable]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build dev tools
        working-directory: ${{github.workspace}}
        run: |
          sudo apt-get install -y git python3
          python3 -m venv env
          env/bin/pip install -r requirements.txt
      - name: Lint python code
        working-directory: ${{github.workspace}}
        run: find . -name '*.py' -print0 | xargs -0 -- git ls-tree --full-tree --name-only -z HEAD -- | xargs -0 -- env/bin/isort --check-only --python-version auto
