---
jobs:
  python:
    concurrency:
      cancel-in-progress: ${{ github.ref != 'refs/heads/stable' }}
      group: ${{ github.workflow }}-${{ github.ref }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.2.0
      - name: MyPy Cache
        uses: actions/cache@v3.0.11
        with:
          key: mypy-${{ github.run_id }}
          path: .mypy_cache
          restore-keys: mypy
      - name: Lint python code
        uses: ./
        with:
          run: |
            python tools/before.py
            python tools/self_check.py

name: Python

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - stable
    paths:
      - .github/workflows/python.yml
      - "**.py"
      - requirements.txt
  push:
    branches:
      - stable
    paths:
      - .github/workflows/python.yml
      - "**.py"
      - requirements.txt
  workflow_dispatch: ~
