---
jobs:
  python:
    concurrency:
      cancel-in-progress: ${{ github.ref != 'refs/heads/stable' }}
      group: self-check-${{ github.workflow }}-${{ github.ref }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.1.0
      - name: MyPy Cache
        uses: actions/cache@v3.0.11
        with:
          key: mypy-${{ github.run_id }}
          path: .mypy_cache
          restore-keys: mypy
      - name: Lint python code
        uses: ./
        with:
          run: |
            python tools/before.py
            python tools/self_check.py
  requirements_txt:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Freeze dependencies
        run: |
          python3 tools/venv.py python3
          env/bin/pip freeze | grep -v -e '^pkg_resources==' >requirements.txt
        working-directory: ${{ github.workspace }}
      - if: ${{ github.ref == 'refs/heads/stable' }}
        uses: stefanzweifel/git-auto-commit-action@v4.16.0
        with:
          branch: requirements-txt
          commit_message: Update requirements.txt.
          create_branch: true
          file_pattern: requirements.txt
          repository: ${{ github.workspace }}
  utf8_generate:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.1.0
      - name: generate utf8 grammar
        uses: ./
        with:
          run: |
            python tools/before.py
            python tools/utf8_generate.py
      - if: ${{ github.ref == 'refs/heads/stable' }}
        uses: stefanzweifel/git-auto-commit-action@v4.16.0
        with:
          branch: utf8-generate-grammar
          commit_message: Update utf8 grammar.
          create_branch: true
          file_pattern: library/grammar
          repository: ${{ github.workspace }}

name: Python

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - stable
    paths:
      - .github/workflows/python.yml
      - "**.py"
      - cmake/**
      - CMakeList.txt
      - requirements.txt
  push:
    branches:
      - stable
    paths:
      - .github/workflows/python.yml
      - "**.py"
      - cmake/**
      - CMakeList.txt
      - requirements.txt
  workflow_dispatch: ~
