---
jobs:
  python:
    concurrency:
      cancel-in-progress: ${{ github.ref != 'refs/heads/stable' }}
      group: ${{ github.workflow }}-${{ github.ref }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          filter: tree:0
      - name: MyPy Cache
        uses: actions/cache@v3.3.3
        with:
          key: mypy-${{ github.run_id }}
          path: .mypy_cache
          restore-keys: mypy-
      - name: Lint python code
        uses: ./
        with:
          run: python tools/self_check.py

name: Python

# yamllint disable-line rule:truthy
on:
  push:
    paths:
      - .github/workflows/python.yml
      - "**.py"
      - action.yml
      - requirements.txt
      - setup.cfg
      - tools/requirements.txt
  workflow_dispatch: ~
