---
jobs:
  mypy:
    concurrency:
      cancel-in-progress: ${{ github.ref != 'refs/heads/stable' }}
      group: mypy-${{ github.workflow }}-${{ github.ref }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.2.0
      - name: MyPy Cache
        uses: actions/cache@v3.0.11
        with:
          key: mypy-${{ github.run_id }}
          path: .mypy_cache
          restore-keys: mypy
      - name: Lint python code
        uses: ./
        with:
          run: >
            python tools/before.py;
            tools/g-ls-tree.sh -not -path './stdlib/*' -name '*.py' |
            xargs --no-run-if-empty --null --
            mypy
  python:
    concurrency:
      cancel-in-progress: ${{ github.ref != 'refs/heads/stable' }}
      group: ${{ matrix.lints }}-${{ github.workflow }}-${{ github.ref }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.2.0
      - name: Lint python code
        uses: ./
        with:
          run: >
            python tools/before.py;
            tools/g-ls-tree.sh -name '*.py' |
            xargs --no-run-if-empty --null --
            ${{ matrix.lints }}
    strategy:
      matrix:
        lints:
          - black --check --diff --preview --target-version py311
          - isort --check-only --python-version auto
          - pylama

name: Python

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - stable
    paths:
      - .github/workflows/python.yml
      - "**.py"
      - requirements.txt
  push:
    branches:
      - stable
    paths:
      - .github/workflows/python.yml
      - "**.py"
      - requirements.txt
  workflow_dispatch: ~
