---
jobs:
  mypy:
    concurrency:
      cancel-in-progress: ${{ github.ref != 'refs/heads/stable' }}
      group: mypy-${{ github.workflow }}-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: deadsnakes/action@v2.1.1
        with:
          python-version: 3.12-dev
      - name: Build dev tools
        run: >
          python3.12 -m venv env &&
          env/bin/pip3 install -r requirements.txt
      - name: Lint python code
        run: >
          find . -not -path './stdlib/*' -name '*.py' -print0 |
          xargs -0 -- git ls-tree --full-tree --name-only -z HEAD -- |
          xargs -0 -- env/bin/mypy
        working-directory: ${{ github.workspace }}
  python:
    concurrency:
      cancel-in-progress: ${{ github.ref != 'refs/heads/stable' }}
      group: ${{ matrix.lints }}-${{ github.workflow }}-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: deadsnakes/action@v2.1.1
        with:
          python-version: 3.12-dev
      - name: Build dev tools
        run: >
          python3.12 -m venv env &&
          env/bin/pip3 install -r requirements.txt
        working-directory: ${{ github.workspace }}
      - name: Lint python code
        run: >
          find . -name '*.py' -print0 |
          xargs -0 -- git ls-tree --full-tree --name-only -z HEAD -- |
          xargs -0 -- env/bin/${{ matrix.lints }}
        working-directory: ${{ github.workspace }}
    strategy:
      matrix:
        lints:
          - black --check --diff --preview --target-version py311
          - isort --check-only --python-version auto
          - pylama

name: Python

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - stable
    paths:
      - .github/workflows/**
      - "**.py"
      - requirements.txt
  push:
    branches:
      - stable
    paths:
      - .github/workflows/**
      - "**.py"
      - requirements.txt
  workflow_dispatch: ~
