---
jobs:
  cleanup:
    concurrency:
      cancel-in-progress: ${{ github.ref != 'refs/heads/stable' }}
      group: ${{ github.workflow }}-${{ github.ref }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0
      - name: Rebase
        uses: ./
        with:
          run: >
            set -x;
            git config --global user.email
            "41898282+github-actions[bot]@users.noreply.github.com";
            git config --global user.name
            "github-actions[bot]";
            python tools/git_rebase_all.py 'python tools/corpus_trim.py';
            git push --force origin ':' || true

name: Rebase

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - stable
  workflow_dispatch: ~
