---
jobs:
  release:
    concurrency:
      cancel-in-progress: false
      group: ${{ github.workflow }}-${{ github.ref }}
    runs-on: ubuntu-22.04
    steps:
      - uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          tag_name: 0.${{ github.run_number }}.0+${{ github.sha }}
          target_commitish: ${{ github.sha }}
name: Release
# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - stable
    paths:
      - .dockerignore
      - .github/workflows/docker.yml
      - .github/workflows/release.yml
      - Dockerfile*
      - requirements.core.txt
      - requirements.txt
      - tools/boot.yml
  schedule:
    - cron: 20 14 * * *
  workflow_dispatch: ~
permissions:
  contents: write
