---
env:
  IMAGE: ghcr.io/asakatida/chimera
jobs:
  release:
    concurrency:
      cancel-in-progress: false
      group: ${{ github.workflow }}-${{ github.ref }}
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: docker/setup-qemu-action@v2.1.0
      - uses: docker/setup-buildx-action@v2.5.0
      - uses: docker/login-action@v2.1.0
        with:
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          username: ${{ github.actor }}
      - uses: docker/build-push-action@v4.0.0
        with:
          file: Dockerfile.python
          push: true
          tags: ${{ env.IMAGE }}:python3.12
      - uses: docker/build-push-action@v4.0.0
        with:
          push: true
          tags: |
            ${{ env.IMAGE }}:0.${{ github.run_number }}.0
            ${{ env.IMAGE }}:latest
      - name: Update tags
        # yamllint disable rule:line-length
        run: >
          set -e -o pipefail;
          sudo apt-get install ripgrep || true;
          rg --files-with-matches --null --regexp "${IMAGE}" |
          xargs --no-run-if-empty --null --verbose --
          sed -E -i
          -e 's#'"${IMAGE}"':[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+#'"${IMAGE}"':0.${{ github.run_number }}.0#g'
        # yamllint enable rule:line-length
      - uses: softprops/action-gh-release@v1
        with:
          body: |
            docker pull ${{ env.IMAGE }}:0.${{ github.run_number }}.0
          generate_release_notes: true
          tag_name: 0.${{ github.run_number }}.0+${{ github.sha }}
          target_commitish: ${{ github.sha }}
      - uses: stefanzweifel/git-auto-commit-action@v4.16.0
        with:
          branch: pin-0.${{ github.run_number }}.0
          commit_message: Update docker tag pins to 0.${{ github.run_number }}.0
          create_branch: true
          repository: ${{ github.workspace }}
name: Release
# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - stable
    paths:
      - .dockerignore
      - .github/workflows/docker.yml
      - .github/workflows/release.yml
      - Dockerfile*
      - requirements.core.txt
      - requirements.txt
      - tools/boot.yml
  schedule:
    - cron: 37 1 * * 2
  workflow_dispatch: ~
