name: Shellcheck

on:
  push:
    branches: [stable]
    paths:
      - ".github/workflows/**"
      - "**.sh"
  pull_request:
    branches: [stable]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build dev tools
        run: sudo apt-get install -y shellcheck
      - name: Lint shell
        working-directory: ${{github.workspace}}
        run: find . -name '*.sh' -print0 | xargs -0 -- git ls-tree --full-tree --name-only -z HEAD -- | xargs -0 -- shellcheck --severity=info --enable=all
