jobs:
  shellcheck:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.workflow }}-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build dev tools
        run: sudo apt-get install -y shellcheck
      - name: Lint shell
        run: find . -name '*.sh' -print0 | xargs -0 -- git ls-tree --full-tree --name-only -z HEAD -- | xargs -0 -- shellcheck --severity=info --enable=all
        working-directory: ${{github.workspace}}

name: Shellcheck

on:
  pull_request:
    branches:
      - stable
    paths:
      - .github/workflows/**
      - "**.sh"
  push:
    branches:
      - stable
    paths:
      - .github/workflows/**
      - "**.sh"
  workflow_dispatch: ~
