name: Shellcheck

on:
  push:
    branches: [stable]
    paths:
      - '.github/workflows/**'
      - '**.sh'
  pull_request:
    branches: [stable]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build dev tools
        run: sudo apt-get install -y git shellcheck
      - name: Lint shell
        working-directory: ${{github.workspace}}
        run: tools/shellcheck.sh
