---
jobs:
  shellcheck:
    concurrency:
      cancel-in-progress: ${{ github.ref != 'refs/heads/stable' }}
      group: ${{ github.workflow }}-${{ github.ref }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Build dev tools
        run: sudo apt-get install -y shellcheck
      - name: Lint shell
        run: >
          find . -name '*.sh' -print0 |
          xargs -0 -- git ls-tree --full-tree --name-only -z HEAD -- |
          xargs -0 --
          shellcheck --enable=all --severity=style --shell=bash --exclude=SC2096
        working-directory: ${{ github.workspace }}

name: Shellcheck

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - stable
    paths:
      - .github/workflows/**
      - "**.sh"
  push:
    branches:
      - stable
    paths:
      - .github/workflows/**
      - "**.sh"
  workflow_dispatch: ~
