---
jobs:
  trufflehog:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.workflow }}-${{ github.ref }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@v3.16.4
        with:
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          path: ./
name: TruffleHog
# yamllint disable-line rule:truthy
on:
  pull_request: ~
  workflow_dispatch: ~
