---
jobs:
  trufflehog:
    concurrency:
      cancel-in-progress: ${{ github.ref != 'refs/heads/stable' }}
      group: ${{ github.workflow }}-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@v3.7.3
        with:
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          path: ./
name: TruffleHog
# yamllint disable-line rule:truthy
on:
  - pull_request
