---
jobs:
  trufflehog:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.workflow }}-${{ github.ref }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.0
        with:
          fetch-depth: 0
          filter: tree:0
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@v3.60.0
        with:
          base: ${{ github.event.repository.default_branch }}
          extra_args: --debug --only-verified
          head: HEAD
          path: ./
name: TruffleHog
# yamllint disable-line rule:truthy
on:
  pull_request: ~
  workflow_dispatch: ~
